language: python
sudo: required
services:
  - docker
install:
  - pip install pep8
  - pip install pylint
script:
  - pep8 --max-line-length=120 --show-source --show-pep8 run.py
  - pylint run.py
  - ./test/travis-test.sh
